### ISSUE TITLE
Upload issue with IATA and ICAO conversion 

### ISSUE THREAD

**Issue by RadarWarning** [ericberman/MyFlightbookWeb#1221] opened 2024-05-04 10:43 UTC
Uploaded airport MAN, intended for Manchester airport in the UK, converted to KMAN instead of EGCC, I can see a conflict here.

https://github.com/ericberman/MyFlightbookWeb/blob/3c0df976abc473190bcd2b59972a6e64e1acef51/MyFlightbook.Web/AppCode/Places/Airports.cs#L570

**Comment by ericberman** [comment] 2024-05-04 16:02
Not a bug in the code.  MAN is inherently a conflict because I have both MAN and KMAN in the database, it's not due to the code you identified.  KMAN is Nampa airport.  I can re-assign to MAN if you think I should (this is why EGCC - i.e., ICAO codes - are preferrable).

**Comment by ericberman** [comment] 2024-05-04 16:08
I'll go ahead and do this, the same way that PVG, which is both Shanghai and Hampton Roads (Virginia); Shanghai is clearly the busier of the two airports., so KPVG goes to Virginia and PVG goes to Shanghai. 

These conflicts are inevitable with multiple naming schemes.

**Closed** 2024-05-04 16:10 UTC
