### ISSUE TITLE
Flights NOT matching specified parameters

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#325] opened 2019-06-24 23:58 UTC
For some searches, it would be helpful to allow the user to specify that the flight NOT match or be described by a specific parameter.   Each separate parameter in a group could be added to the query with (AND NOT x) or (OR NOT x).

A possible UI would be to have a multi-click box before each parameter with visual alternatives  like  ✅ and X and a blank box.

**Comment by ericberman** [comment] 2019-06-29 20:15
Duplicate of issue #323; I get that one is within a group of parameters and one is for the group as a whole, but the larger issue is "how do you support AND/OR/NOT in search."

**Closed by ericberman** 2019-06-29 20:15 UTC
