### ISSUE TITLE
Issues with Playpen -> create flights from Telemetry

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#629] opened 2020-07-15 01:31 UTC
1. The attached Flightaware telemetry files (in a .zip file) created three pending flights.   They should have all been either KGPI-8S1 or 8S1-KGPI.  One of them indicates a route consisting of "27MT".   As displayed in Flightaware, they were designated as 8S1.

2. Since none of these three flights were local, shouldn't they have a take-off and landing airport?

3. When editing a pending flight created from telemetry, there is an indication that "This flight has associated data".  It looks like a URL, but nothing happens when I click on that text.  For a non-pending flight, the Flight Details page is displayed.   It is useful, while editing a pending flight created from telemetry, to be able to see the track log to assist in filling in the blanks.

4. Can you please make the timezone for creating flights from telemetry sticky?

5. Bonus request:  I of course have created a bookmark to visit the playpen.  But it would be handy if there were a link from the actual site directly to the playpen.   This could be relatively hidden (say in the footer?), but giving the playpen more visibility might generate more use of these "pending" (?) features.   Then you'd get more feedback on their utility and any issues that have to be addressed.

[N262WH flights.zip](https://github.com/ericberman/MyFlightbookWeb/files/4922327/N262WH.flights.zip)

**Comment by KayRJay** [comment] 2020-07-15 02:17
One more thing ... the Flight Details page opens a new browser tab, but for some reason the tab's URL is "on mm/dd/yy", and not something like "Pending flight details".

**Comment by ericberman** [comment] 2020-07-15 03:28
Issues 1 and 2: This is a data issue.  The usual GIGO problem - I do the best I can with the data I'm given.
 * For all three flights, I see the speed rise above a threshold takeoff speed, but I never see the speed drop below the corresponding landing speed (typically ~0.85 of the takeoff speed).  So I never record a landing.  FlightAware seems to suck at that.  If using telemetry, I strongly recommend using a mobile app or your aircraft's GPS or similar and actually measuring it.  I can't distinguish "GPS recording simply ended" from "You landed", so I don't record a landing if I don't see the speed drop.  That's by design.
 * You're seeing 27MT because the first point I see on that flight is at 48.32173N/114.29829W, which is closer to 27MT than it is to 8S1 or KGPI.  GIGO.  I use the nearest airport to the first point of flight as your departure airport; I'm not sure what else could possibly make sense here.  Again, the FlightAware data is pretty crappy; I recommend using a better data source

For #3: that's actually a bunch of work, since all of the stuff to view telemetry requires that the telemetry be in the database already; pending flights are kinda by definition off-to-the-side, and by definition have not passed any sort of validation.   I'm going to punt on that.

For #4: the problem is that airplanes cross a lot of time zone boundaries, making assumptions about time zone sketchy at best.  If the data is all UTC (as GPX and KML are), then it's a non-issue, but if it's CSV and in local time (you'd be surprised...) then I need you to do this.  

For #5 - I could do this, but I won't.  Yes, the playpen exists to get feedback, but mostly it's for quick-and-dirty stuff that has very low demand (or is for my personal use) and where the investment to do it to "deployment" standards is simply not justified by the amount of usage or support requests I'd get.  Very much by definition - this is NOT supported functionality.  If I add a visible link or anything that can bypass the disclaimers, then it becomes supported, and I end up fielding product support requests/bugs/questions, which is PRECISELY what I am trying to avoid.  A lot of what's here is wonky, fragile, or otherwise super hard to get up to full-standards.  The entire point of putting it into a playpen off to the side is so that I can occasionally point someone to it when necessary, but not be obligated to fix bugs, apply fit and finish, (see #4 above), and so forth.  If stuff here breaks, I can legitimately say "oh, well", which I can't do for other functionality.  Anything I do to make it more visible for people to stumble upon violates that.

I have promoted functionality from the playpen in the past; at that point, it comes **out** of the playpen because - again, by definition - at that point it is no longer playpen functionality; it is a "feature", and I support it.  

I'm confused about your thing about the Flight Details page in the browser tab and the "on mm/dd/yy".  When I click on a pending flight, it neither opens in a new tab nor says "on mm/dd/yy".  (I don't specify a title for the page, so at least in firefox, the tab simply has the URL of the page...)

**Comment by ericberman** [comment] 2020-07-15 03:36
Just to hit home on the 27MT vs. KGPI issue:
![image](https://user-images.githubusercontent.com/16455286/87500582-b0224100-c611-11ea-8d30-16e5c5fdd0d8.png)

**Comment by ericberman** [comment] 2020-07-16 17:39
Oh, on #4: it was already sticky per session, but I'm now defaulting it to your preferred timezone, if you've specified one.

**Closed** 2020-07-16 20:28 UTC
